name: Python Conda CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10
        auto-activate-base: false
        environment-file: environment.yml
        activate-environment: test-env  # Match the name in your environment.yml
        use-mamba: true

    - name: Install test/lint tools (flake8, pytest)
      shell: bash -l {0}
      run: |
        conda install -y flake8 pytest

    - name: Lint
      shell: bash -l {0}
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
